{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d4945d8e-d5c7-4b6b-b41b-363abfb4385b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pygame 2.5.1 (SDL 2.28.2, Python 3.9.16)\n",
      "Hello from the pygame community. https://www.pygame.org/contribute.html\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\user\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py:3513: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import pygame\n",
    "import sys\n",
    "import math\n",
    "from pygame.locals import *\n",
    "\n",
    "WHITE  =  (255,255,255)\n",
    "BLACK  =  (  0,  0,  0)\n",
    "SILVER =  (192,208,224)\n",
    "RED    =  (255,  0,  0)\n",
    "CYAN   =  (  0,224,255)\n",
    "YELLOW =  (255,224,  0)\n",
    "GREEN  =  (  0,255,  0)\n",
    "\n",
    "\n",
    "\n",
    "# 背景の読み込み\n",
    "img_galaxy = pygame.image.load(\"image_gl/galaxy.png\")\n",
    "\n",
    "img_title = [pygame.image.load(\"image_gl/nebula.png\")]\n",
    "\n",
    "\n",
    "se_barrage = None\n",
    "se_damage = None\n",
    "se_explosion = None\n",
    "se_shot = None\n",
    "\n",
    "\n",
    "idx = 0\n",
    "tmr = 0\n",
    "timetimr = 0\n",
    "bg_x = 0\n",
    "bg_y = 0\n",
    "\n",
    "# 手前側プレイヤー\n",
    "img_sship = [\n",
    "    pygame.image.load(\"image_gl/starship.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_l.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_r.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_burner.png\")\n",
    "]\n",
    "\n",
    "img_weapon = pygame.image.load(\"image_gl/bullet.png\")\n",
    "img_sub = pygame.image.load(\"image_gl/enemy0.png\")\n",
    "\n",
    "img_shield = pygame.image.load(\"image_gl/shield.png\")\n",
    "\n",
    "\n",
    "img_explode = [\n",
    "    None,\n",
    "    pygame.image.load(\"image_gl/explosion1.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion2.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion3.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion4.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion5.png\")\n",
    "]\n",
    "\n",
    "win1 = 0\n",
    "p1_count = 0\n",
    "score = 0\n",
    "HI_SCORE = 0\n",
    "\n",
    "ss_x = 0\n",
    "ss_y = 0\n",
    "ss_d = 0\n",
    "ss_shield = 0\n",
    "ss_muteki = 0\n",
    "\n",
    "\n",
    "\n",
    "key_spc = 0\n",
    "\n",
    "MISSILE_MAX = 3\n",
    "msl_no = 0\n",
    "msl_f = [False]*MISSILE_MAX\n",
    "msl_x = [0]*MISSILE_MAX\n",
    "msl_y = [0]*MISSILE_MAX\n",
    "\n",
    "\n",
    "key_m = 0\n",
    "\n",
    "MISSILE_MAX_1 = 2\n",
    "msl_noo = 0\n",
    "msl_ff = [False]*MISSILE_MAX_1\n",
    "msl_xx = [0]*MISSILE_MAX_1\n",
    "msl_yy = [0]*MISSILE_MAX_1\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "EFFECT_MAX = 100\n",
    "eff_no = 0\n",
    "eff_p = [0]*EFFECT_MAX\n",
    "eff_x = [0]*EFFECT_MAX\n",
    "eff_y = [0]*EFFECT_MAX\n",
    "\n",
    "\n",
    "\n",
    "# 上側プレイヤー\n",
    "img_sship2 = [\n",
    "    pygame.image.load(\"image_gl/starship.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_l.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_r.png\"),\n",
    "    pygame.image.load(\"image_gl/starship_burner.png\")\n",
    "]\n",
    "\n",
    "img_weapon2 = pygame.image.load(\"image_gl/bullet.png\")\n",
    "img_sub2 = pygame.image.load(\"image_gl/enemy0.png\")\n",
    "\n",
    "img_shield2 = pygame.image.load(\"image_gl/shield.png\")\n",
    "\n",
    "\n",
    "img_explode2 = [\n",
    "    None,\n",
    "    pygame.image.load(\"image_gl/explosion1.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion2.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion3.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion4.png\"),\n",
    "    pygame.image.load(\"image_gl/explosion5.png\")\n",
    "]\n",
    "\n",
    "win2 = 0\n",
    "p2_count = 0\n",
    "score2 = 0\n",
    "HI_SCORE2 = 0\n",
    "\n",
    "ss_x2 = 0\n",
    "ss_y2 = 0\n",
    "ss_d2 = 0\n",
    "ss_shield2 = 0\n",
    "#ss_muteki2 = 0\n",
    "\n",
    "\n",
    "key_spc2 = 0\n",
    "\n",
    "MISSILE_MAX2 = 3\n",
    "msl_no2 = 0\n",
    "msl_f2 = [False]*MISSILE_MAX2\n",
    "msl_x2 = [0]*MISSILE_MAX2\n",
    "msl_y2 = [0]*MISSILE_MAX2\n",
    "\n",
    "\n",
    "key_v = 0\n",
    "\n",
    "MISSILE_MAX_2 = 2\n",
    "msl_noo2 = 0\n",
    "msl_fff = [False]*MISSILE_MAX_2\n",
    "msl_xxx = [0]*MISSILE_MAX_2\n",
    "msl_yyy = [0]*MISSILE_MAX_2\n",
    "\n",
    "\n",
    "\n",
    "EFFECT_MAX2 = 100\n",
    "eff_no2 = 0\n",
    "eff_p2 = [0]*EFFECT_MAX2\n",
    "eff_x2 = [0]*EFFECT_MAX2\n",
    "eff_y2 = [0]*EFFECT_MAX2\n",
    "\n",
    "\n",
    "\n",
    "def get_dis(x1,y1,x2,y2):\n",
    "    return ( (x1-x2)*(x1-x2) + (y1-y2)*(y1-y2) )\n",
    "    \n",
    "\n",
    "def draw_text(scrn, txt, x, y ,siz, col):\n",
    "    fnt = pygame.font.Font(None, siz)\n",
    "    sur = fnt.render(txt, True, col)\n",
    "    x = x - sur.get_width()/2\n",
    "    y = y - sur.get_height()/2\n",
    "    scrn.blit(sur, [x,y])\n",
    "\n",
    "    \n",
    "def draw_text2(scrn2, txt2, x2, y2 ,siz2, col2):\n",
    "    fnt2 = pygame.font.Font(None, siz2)\n",
    "    sur2 = fnt2.render(txt2, True, col2)\n",
    "    x2 = x2 - sur2.get_width()/2\n",
    "    y2 = y2 - sur2.get_height()/2\n",
    "    scrn2.blit(sur2, [x2,y2])\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "def move_starship(scrn, key):\n",
    "    global ss_x, ss_x2, ss_y, ss_y2,ss_d, key_spc, ss_shield, ss_shield2, ss_muteki, score,score2, timetmr, key_m, set_effect\n",
    "    \n",
    "    ss_d = 0\n",
    "    if key[K_w] == 1:\n",
    "        ss_y = ss_y - 8\n",
    "        score += 2\n",
    "        ss_shield += 0.02\n",
    "        if ss_y < 60:\n",
    "            ss_y = 60\n",
    "            score -= 3\n",
    "            ss_shield -= 0.5\n",
    "            \n",
    "    if key[K_s] == 1:\n",
    "        ss_y = ss_y + 8\n",
    "        score -= 1\n",
    "        if ss_y > 640:\n",
    "            ss_y = 640\n",
    "            score -= 3\n",
    "            ss_shield -= 0.5\n",
    "            \n",
    "    if key[K_a] == 1:\n",
    "        ss_d = 1\n",
    "        ss_x = ss_x - 8\n",
    "        score += 1\n",
    "        ss_shield += 0.01\n",
    "        if ss_x < 60:\n",
    "            ss_x = 60\n",
    "            score -= 3\n",
    "            ss_shield -= 0.5\n",
    "            \n",
    "    if key[K_d] == 1:\n",
    "        ss_d = 2\n",
    "        score += 1\n",
    "        ss_shield += 0.01\n",
    "        ss_x = ss_x + 8\n",
    "        if ss_x > 920:\n",
    "            ss_x = 920\n",
    "            score -= 3\n",
    "            ss_shield -= 0.5\n",
    "    \n",
    "    key_spc = (key_spc+1)*key[K_r]\n",
    "    \n",
    "    if key_spc%20 == 1:\n",
    "        set_missile(0)\n",
    "        se_shot.play()\n",
    "        score -= 70\n",
    "        ss_y += 2\n",
    "        \n",
    "        if ss_y > 640:\n",
    "            ss_y = 620\n",
    "            score -= 100\n",
    "            ss_shield -= 5\n",
    "\n",
    "    \n",
    "    key_m = (key_m+1)* key[K_t]\n",
    "\n",
    "    if key_m%512 == 1:\n",
    "        set_missile(10)\n",
    "        se_barrage.play()\n",
    "        score -= 100\n",
    "        ss_y += 5\n",
    "        \n",
    "        if ss_y > 640:\n",
    "            ss_y = 620\n",
    "            score -= 200\n",
    "            ss_shield -= 5\n",
    "        \n",
    "    \n",
    "                \n",
    "                \n",
    "                \n",
    "    \n",
    "        \n",
    "    \n",
    "    \n",
    "    if img_sship != img_weapon:\n",
    "        w = img_weapon.get_width() - 7\n",
    "        h = img_weapon.get_height() - 7\n",
    "        r = int((w+h/4) + (1)/4)\n",
    "        \n",
    "        \n",
    "        for n in range(MISSILE_MAX):\n",
    "            if msl_f[n] == True and get_dis(msl_x[n], msl_y[n], ss_x2, ss_y2) < r*r:\n",
    "                set_effect2(msl_x[n], msl_y[n])\n",
    "                se_damage.play()\n",
    "                \n",
    "                if ss_shield > 0 and ss_shield2 > 0 and timetmr >= 0:\n",
    "                    ss_shield2 = ss_shield2 - 1.3\n",
    "                    score += 150\n",
    "                    ss_y2 -= 4\n",
    "                    \n",
    "                    if ss_y2 < 60:\n",
    "                        score -= 100\n",
    "                        ss_shield2 -= 3\n",
    "                        ss_y2 = 80\n",
    "                \n",
    "        for i in range(MISSILE_MAX_1):\n",
    "            if msl_ff[i] == True and get_dis(msl_xx[i], msl_yy[i], ss_x2, ss_y2) < r*r:\n",
    "                set_effect2(msl_xx[i], msl_yy[i])\n",
    "                se_damage.play()\n",
    "                \n",
    "                if ss_shield > 0 and ss_shield2 > 0 and timetmr >= 0:\n",
    "                    ss_shield2 = ss_shield2 - 2\n",
    "                    score += 300\n",
    "                    ss_y2 -= 7\n",
    "                    \n",
    "                    if ss_y2 < 60:\n",
    "                        score2 -= 100\n",
    "                        ss_shield2 -= 3\n",
    "                        ss_y2 = 60\n",
    "\n",
    "        \n",
    "        \n",
    "    \n",
    "    P = get_dis(ss_x, ss_y, ss_x2, ss_y2)\n",
    "    A = (P/12000000) \n",
    "    \n",
    "    S = 1 - A\n",
    "    \n",
    "    \n",
    "    img_wide_away = pygame.transform.rotozoom(img_sship[ss_d], 0, S)\n",
    "    scrn.blit(img_wide_away,[ss_x-37,ss_y-48])\n",
    "    \n",
    "    #img_wide_away2 = pygame.transform.rotozoom(img_sship2[3], 0, S)\n",
    "    #scrn.blit(img_wide_away2, [ss_x-7*(S*1.1), ss_y+39*(S*0.9983)+(tmr%3)*2])\n",
    "    \n",
    "\n",
    "def set_missile(typ): # 自機の発射する弾をセットする\n",
    "    global msl_no, msl_noo\n",
    "    if typ == 0:\n",
    "        msl_f[msl_no] = True\n",
    "        msl_x[msl_no] = ss_x-3\n",
    "        msl_y[msl_no] = ss_y-50\n",
    "        msl_no = (msl_no+1)%MISSILE_MAX\n",
    "    if typ == 10:\n",
    "        msl_ff[msl_noo] = True\n",
    "        msl_xx[msl_noo] = ss_x-6\n",
    "        msl_yy[msl_noo] = ss_y+110\n",
    "        #msl_a[msl_noo] = a\n",
    "        msl_noo = (msl_noo+1)%MISSILE_MAX_1\n",
    "\n",
    "        \n",
    "\n",
    "        \n",
    "def move_missile(scrn):# 弾の移動\n",
    "    for i in range(MISSILE_MAX):\n",
    "        if msl_f[i] == True:\n",
    "            msl_y[i] = msl_y[i] - 15\n",
    "            main_one = pygame.transform.rotozoom(img_weapon, 0, 0.8)\n",
    "            scrn.blit(main_one, [msl_x[i]-8, msl_y[i]-32])\n",
    "\n",
    "            if msl_y[i] < 0:\n",
    "                msl_f[i] = False\n",
    "    \n",
    "    \n",
    "    for i in range(MISSILE_MAX_1):\n",
    "        if msl_ff[i] == True:\n",
    "            msl_yy[i] = msl_yy[i] -37\n",
    "            main_two = pygame.transform.rotozoom(img_sub, 0, 1.2)\n",
    "            scrn.blit(main_two, [msl_xx[i]-8, msl_yy[i]-32])\n",
    "\n",
    "            if msl_yy[i] < 0:\n",
    "                msl_ff[i] = False\n",
    "\n",
    "\n",
    "                \n",
    "                \n",
    "                \n",
    "                \n",
    "def set_effect(x, y): # 爆発をセットする\n",
    "    global eff_no\n",
    "    eff_p[eff_no] = 1\n",
    "    eff_x[eff_no] = x\n",
    "    eff_y[eff_no] = y\n",
    "    eff_no = (eff_no+1)%EFFECT_MAX\n",
    "\n",
    "\n",
    "def draw_effect(scrn): # 爆発の演出\n",
    "    for i in range(EFFECT_MAX):\n",
    "        if eff_p[i] > 0:\n",
    "            scrn.blit(img_explode[eff_p[i]], [eff_x[i]-48+(tmr%3)*10, eff_y[i]-48])\n",
    "            eff_p[i] = eff_p[i] + 1\n",
    "            if eff_p[i] == 6:\n",
    "                eff_p[i] = 0\n",
    "\n",
    "\n",
    "\n",
    "                \n",
    "def move_starship2(scrn2, key2,):\n",
    "    global ss_x, ss_x2, ss_y, ss_y2, ss_d2, key_spc2, ss_shield, ss_shield2, ss_muteki2, score, score2, timetmr, key_v, set_effect2\n",
    "    ss_d2 = 0\n",
    "    if key2[K_UP] == 1:\n",
    "        ss_y2 = ss_y2 - 8\n",
    "        score2 -= 1\n",
    "        if ss_y2 < 60:\n",
    "            ss_y2 = 60\n",
    "            score2 -= 3\n",
    "            ss_shield2 -= 0.5\n",
    "            \n",
    "            \n",
    "    if key2[K_DOWN] == 1:\n",
    "        ss_y2 = ss_y2 + 8\n",
    "        score2 += 2\n",
    "        ss_shield2 += 0.02\n",
    "        if ss_y2 > 640:\n",
    "            ss_y2 = 640\n",
    "            score2 -= 3\n",
    "            ss_shield2 -= 0.5\n",
    "            \n",
    "    if key2[K_LEFT] == 1:\n",
    "        ss_d2 = 2\n",
    "        ss_x2 = ss_x2 - 8\n",
    "        score2 += 1\n",
    "        ss_shield2 += 0.01\n",
    "        if ss_x2 < 60:\n",
    "            ss_x2 = 60\n",
    "            score2 -= 3\n",
    "            ss_shield2 -= 0.5\n",
    " \n",
    "            \n",
    "    if key2[K_RIGHT] == 1:\n",
    "        ss_d2 = 1\n",
    "        score2 += 1\n",
    "        ss_shield2 += 0.01\n",
    "        ss_x2 = ss_x2 + 8\n",
    "        if ss_x2 > 920:\n",
    "            ss_x2 = 920\n",
    "            score2 -= 3\n",
    "            ss_shield2 -= 0.5\n",
    " \n",
    "    \n",
    "    key_spc2 = (key_spc2+1)*key2[K_KP2]\n",
    "    \n",
    "    if key_spc2%20 == 1:\n",
    "        set_missile2(1)\n",
    "        se_shot.play()\n",
    "        score2 -= 70\n",
    "        ss_y2 -= 2\n",
    "        \n",
    "        if ss_y2 < 60:\n",
    "            ss_y2 = 80\n",
    "            score2 -= 100\n",
    "            ss_shield2 -= 5\n",
    "        \n",
    "        \n",
    "    key_v = (key_v+1)* key2[K_KP3]\n",
    "    if key_v%512 == 1:\n",
    "        set_missile2(11)\n",
    "        se_barrage.play()\n",
    "        score2 -= 100\n",
    "        ss_y2 -= 5\n",
    "        \n",
    "        if ss_y2 < 60:\n",
    "            ss_y2 = 80\n",
    "            score2 -= 200\n",
    "            ss_shield2 -= 5\n",
    "        \n",
    "        \n",
    "           \n",
    "    \n",
    "    \n",
    "    \n",
    "    if img_sship2 != img_weapon2:\n",
    "        w = img_weapon2.get_width() - 7\n",
    "        h = img_weapon2.get_height() - 7\n",
    "        r = int((w+h/4) + (1)/4)\n",
    "\n",
    "\n",
    "        # 2pメインウェポン\n",
    "        for n in range(MISSILE_MAX2):\n",
    "                if msl_f2[n] == True and get_dis(msl_x2[n], msl_y2[n], ss_x, ss_y) < r*r:\n",
    "                    set_effect(msl_x2[n], msl_y2[n])\n",
    "                    se_damage.play()\n",
    "\n",
    "                    if ss_shield > 0 and ss_shield2 > 0 and timetmr >= 0:\n",
    "                        ss_shield = ss_shield - 1.3\n",
    "                        score2 += 150\n",
    "                        ss_y += 4\n",
    "\n",
    "                        if ss_y > 630:\n",
    "                            score2 -= 100\n",
    "                            ss_shield -= 3\n",
    "                            ss_y = 610\n",
    "\n",
    "                    \n",
    "        # 2pサブウェポン当たり判定\n",
    "        for i in range(MISSILE_MAX_2):\n",
    "            if msl_fff[i] == True and get_dis(msl_xxx[i], msl_yyy[i], ss_x, ss_y) < r*r:\n",
    "                set_effect(msl_xxx[i], msl_yyy[i])\n",
    "                se_damage.play()\n",
    "                \n",
    "                if ss_shield2 > 0 and ss_shield > 0 and timetmr >= 0:\n",
    "                    ss_shield = ss_shield - 2\n",
    "                    score2 += 300\n",
    "                    ss_y += 7\n",
    "                    \n",
    "                    if ss_y > 630:\n",
    "                        score-= 100\n",
    "                        ss_shield -= 3\n",
    "                        ss_y = 630\n",
    "        \n",
    "        \n",
    "       \n",
    "                \n",
    "    P2 = get_dis(ss_x, ss_y, ss_x2, ss_y2)\n",
    "    A2 = (P2/12000000) \n",
    "\n",
    "    S2 = 1 - A2\n",
    "                \n",
    "                \n",
    "                \n",
    "    # ２ｐの自機の表示            \n",
    "    img_rz = pygame.transform.rotozoom(img_sship2[ss_d2], 180, S2)\n",
    "    scrn2.blit(img_rz,[ss_x2-37,ss_y2-48])\n",
    "        \n",
    "        \n",
    "    # ２ｐの炎のエフェクト\n",
    "    #img_rzzz = pygame.transform.rotozoom(img_sship2[3], 180, S)\n",
    "    #scrn2.blit(img_rzzz, [ss_x2-11.5*(S*1.1), ss_y2-84.5*(S*0.9983)+(tmr%3)*2])\n",
    "        \n",
    "            \n",
    "    \n",
    "def set_missile2(typ2):\n",
    "    global msl_no2, msl_noo2\n",
    "    if typ2 == 1:\n",
    "        msl_f2[msl_no2] = True\n",
    "        msl_x2[msl_no2] = ss_x2 \n",
    "        msl_y2[msl_no2] = ss_y2\n",
    "        msl_no2 = (msl_no2+1)%MISSILE_MAX2\n",
    "    if typ2 == 11:\n",
    "        msl_fff[msl_noo2] = True\n",
    "        msl_xxx[msl_noo2] = ss_x2 -6\n",
    "        msl_yyy[msl_noo2] = ss_y2-110\n",
    "        #msl_a[msl_noo] = a\n",
    "        msl_noo2 = (msl_noo2+1)%MISSILE_MAX_2\n",
    "\n",
    "\n",
    "\n",
    "            \n",
    "def move_missile2(scrn2):\n",
    "    for i in range(MISSILE_MAX2):\n",
    "        if msl_f2[i] == True:\n",
    "            msl_y2[i] = msl_y2[i] + 15\n",
    "            img_rzz = pygame.transform.rotozoom(img_weapon2, 180, 0.8)\n",
    "            scrn2.blit(img_rzz, [msl_x2[i]-10, msl_y2[i]+25])\n",
    "             \n",
    "            \n",
    "            if msl_y2[i] > 720:\n",
    "                msl_f2[i] = False\n",
    "    \n",
    "    \n",
    "    for i in range(MISSILE_MAX_2):\n",
    "        if msl_fff[i] == True:\n",
    "            msl_yyy[i] = msl_yyy[i] + 37\n",
    "            img_rzzzz = pygame.transform.rotozoom(img_sub2, 180, 1.2)\n",
    "            scrn2.blit(img_rzzzz, [msl_xxx[i]-10, msl_yyy[i]+25])\n",
    "            \n",
    "            \n",
    "            \n",
    "            if msl_yyy[i] > 720:\n",
    "                msl_fff[i] = False\n",
    "\n",
    "\n",
    "                \n",
    "def set_effect2(x2, y2): # 爆発をセットする\n",
    "    global eff_no2\n",
    "    eff_p2[eff_no2] = 1\n",
    "    eff_x2[eff_no2] = x2\n",
    "    eff_y2[eff_no2] = y2\n",
    "    eff_no2 = (eff_no2+1)%EFFECT_MAX2\n",
    "\n",
    "\n",
    "def draw_effect2(scrn2): # 爆発の演出\n",
    "    for i in range(EFFECT_MAX2):\n",
    "        if eff_p2[i] > 0:\n",
    "            scrn2.blit(img_explode2[eff_p2[i]], [eff_x2[i]-48+(tmr%3)*10, eff_y2[i]-48])\n",
    "            eff_p2[i] = eff_p2[i] + 1\n",
    "            if eff_p2[i] == 6:\n",
    "                eff_p2[i] = 0\n",
    "\n",
    "    \n",
    "\n",
    "    \n",
    "def main():\n",
    "    global idx,tmr,tmr1, bg_y, ss_x, ss_y, ss_x2, ss_y2, score, score2, ss_shield, ss_shield2, timetmr, HI_SCORE, HI_SCORE2, win1, win2, p1_count, p2_count\n",
    "    global se_barrage, se_damage, se_explosion, se_shot\n",
    "    pygame.init()\n",
    "    pygame.display.set_caption(\"Galaxy Lancer\")\n",
    "    screen = pygame.display.set_mode((1420, 720))\n",
    "    clock = pygame.time.Clock()\n",
    "    se_barrage = pygame.mixer.Sound(\"sound_gl/ロボットを殴る1.mp3\")\n",
    "    se_damage = pygame.mixer.Sound(\"sound_gl/ロボットを殴る1.mp3\")\n",
    "    se_explosion = pygame.mixer.Sound(\"sound_gl/explosion.ogg\")\n",
    "    se_shot = pygame.mixer.Sound(\"sound_gl/ロボットを殴る3.mp3\")\n",
    "    font = pygame.font.Font(None, 80)\n",
    "    colortmr = 0\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    while True:\n",
    "        tmr = tmr + 1\n",
    "        for event in pygame.event.get():\n",
    "            if event.type == QUIT:\n",
    "                pygame.quit()\n",
    "                sys.exit()\n",
    "            if event.type == KEYDOWN:\n",
    "                if event.key == pygame.K_F1:\n",
    "                    screen = pygame.display.set_mode((960, 720), FULLSCREEN)\n",
    "                if event.key == K_F2 or event.key == K_ESCAPE:\n",
    "                    screen = pygame.display.set_mode((960, 720))\n",
    "        \n",
    "        # 背景のスクロール\n",
    "        bg_y = (bg_y+4)%720\n",
    "        screen.blit(img_galaxy, [0, bg_y-720])\n",
    "        screen.blit(img_galaxy, [0, bg_y])\n",
    "\n",
    "        key = pygame.key.get_pressed()\n",
    "        \n",
    "        if idx == 0: # タイトル\n",
    "            img_rz = pygame.transform.rotozoom(img_title[0], -tmr%360, 1.0)\n",
    "            screen.blit(img_rz, [480-img_rz.get_width()/2, 280-img_rz.get_height()/2])\n",
    "            draw_text(screen, \"Zebra\", 460, 320, 70, BLACK)\n",
    "            draw_text(screen, \"Press [Y] to start!\", 480, 600, 50, SILVER)\n",
    "            if key[K_y] == 1:\n",
    "                idx = 1\n",
    "                tmr = 0\n",
    "                timetmr = 2500\n",
    "                p1_count = 0\n",
    "                win1 = 0\n",
    "                win2 = 0\n",
    "                score = 2700\n",
    "                HI_SCORE = 2700\n",
    "                ss_x = 370\n",
    "                ss_y = 290\n",
    "                #ss_d = 0\n",
    "                ss_shield = 100\n",
    "                #ss_muteki = 0\n",
    "                for i in range(MISSILE_MAX):\n",
    "                    msl_f[i] = False\n",
    "                for i in range(MISSILE_MAX_1):\n",
    "                    msl_f[i] = False\n",
    "                \n",
    "                score2 = 2700\n",
    "                HI_SCORE = 2700\n",
    "                ss_x2 = 600\n",
    "                ss_y2 = 480\n",
    "                #ss_d = 0\n",
    "                ss_shield2 = 100\n",
    "                #ss_muteki = 0\n",
    "                for i in range(MISSILE_MAX2):\n",
    "                    msl_f[i] = False\n",
    "                for i in range(MISSILE_MAX_2):\n",
    "                    msl_f[i] = False\n",
    "                pygame.mixer.music.set_volume(0.5)    \n",
    "                pygame.mixer.music.load(\"sound_gl/mixkit-savana-186.mp3\")\n",
    "                pygame.mixer.music.play(-1)\n",
    "                \n",
    "            \n",
    "        if idx == 1.5: \n",
    "            idx = 1\n",
    "            tmr = 0\n",
    "            timetmr = 2500\n",
    "            p1_count = 0\n",
    "            HI_SCORE = 2700\n",
    "            score = 2700\n",
    "            ss_x = 370\n",
    "            ss_y = 290\n",
    "            #ss_d = 0\n",
    "            ss_shield = 100\n",
    "            #ss_muteki = 0\n",
    "            for i in range(MISSILE_MAX):\n",
    "                msl_f[i] = False\n",
    "            for i in range(MISSILE_MAX_1):\n",
    "                msl_f[i] = False\n",
    "\n",
    "\n",
    "            score2 = 2700\n",
    "            HI_SCORE2 = 2700\n",
    "            ss_x2 = 600\n",
    "            ss_y2 = 480\n",
    "            #ss_d = 0\n",
    "            ss_shield2 = 100\n",
    "            #ss_muteki = 0\n",
    "            for i in range(MISSILE_MAX2):\n",
    "                msl_f[i] = False\n",
    "            for i in range(MISSILE_MAX_2):\n",
    "                msl_f[i] = False\n",
    "\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "                    \n",
    "        \n",
    "                    \n",
    "        \n",
    "        if idx == 1:\n",
    "            if timetmr > 0:\n",
    "                timetmr -= 1\n",
    "            colortmr += 0.055\n",
    "            col = (colortmr%256, 0, 0)\n",
    "            pygame.draw.rect(screen, col,[960,0,1400, 700])\n",
    "\n",
    "            sur = font.render(\"TIME \" + str(timetmr), True, WHITE)\n",
    "            screen.blit(sur, [1000,300])\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "            if timetmr != 0:\n",
    "            \n",
    "                if score2 > HI_SCORE2 and timetmr > 0:\n",
    "                    HI_SCORE2 = score2\n",
    "\n",
    "\n",
    "                if score > HI_SCORE and timetmr > 0:\n",
    "                    HI_SCORE = score\n",
    "\n",
    "\n",
    "            \n",
    "            # 体当たり判定    \n",
    "            if get_dis(ss_x, ss_y, ss_x2, ss_y2) < 70*70:\n",
    "                se_barrage.play()\n",
    "                \n",
    "                set_effect(ss_x, ss_y)\n",
    "\n",
    "                if ss_x < ss_x2 and ss_y < ss_y2:\n",
    "                    ss_x -= 100\n",
    "                    ss_y -= 100\n",
    "                    ss_x2 += 100\n",
    "                    ss_y2 += 100\n",
    "\n",
    "                    ss_shield -= 3\n",
    "                    ss_shield2 -= 3\n",
    "\n",
    "\n",
    "                if ss_x > ss_x2 and ss_y < ss_y2:\n",
    "                    ss_x += 100\n",
    "                    ss_y -= 100\n",
    "                    ss_x2 -= 100\n",
    "                    ss_y2 += 100\n",
    "\n",
    "                    ss_shield -= 3\n",
    "                    ss_shield2 -= 3\n",
    "\n",
    "\n",
    "                if ss_x < ss_x2 and ss_y > ss_y2:\n",
    "                    ss_x -= 100\n",
    "                    ss_y += 100\n",
    "                    ss_x2 += 100\n",
    "                    ss_y2 -= 100\n",
    "\n",
    "                    ss_shield -= 3\n",
    "                    ss_shield2 -= 3\n",
    "\n",
    "\n",
    "\n",
    "                if ss_x > ss_x2 and ss_y > ss_y2:\n",
    "                    ss_x += 100\n",
    "                    ss_y += 100\n",
    "                    ss_x2 -= 100\n",
    "                    ss_y2 -= 100\n",
    "\n",
    "                    ss_shield -= 3\n",
    "                    ss_shield2 -= 3\n",
    "\n",
    "\n",
    "\n",
    "                if ss_x < 40:\n",
    "                    ss_x = 440\n",
    "                    ss_shield -= 5\n",
    "\n",
    "                if ss_x2 < 40:\n",
    "                    ss_x2 = 440\n",
    "                    ss_shield2 -= 5\n",
    "\n",
    "\n",
    "                if ss_x > 920:\n",
    "                    ss_x = 512\n",
    "                    ss_shield -= 10\n",
    "\n",
    "                if ss_x2 > 920:\n",
    "                    ss_x2 = 512\n",
    "                    ss_shield2 -= 10\n",
    "\n",
    "\n",
    "                if ss_y < 20:\n",
    "                    ss_y = 320\n",
    "                    ss_shield -= 15\n",
    "\n",
    "                if ss_y2 < 20:\n",
    "                    ss_y2 = 320\n",
    "                    ss_shield2 -= 5\n",
    "\n",
    "\n",
    "                if ss_y > 640:\n",
    "                    ss_y = 340\n",
    "                    ss_shield -= 5\n",
    "\n",
    "                if ss_y2 > 640:\n",
    "                    ss_y2 = 340\n",
    "                    ss_shield2 -= 15\n",
    "\n",
    "                \n",
    "    \n",
    "\n",
    "            \n",
    "            key = pygame.key.get_pressed()\n",
    "            move_starship(screen, key)\n",
    "            move_missile(screen)\n",
    "            draw_effect(screen)\n",
    "            draw_text(screen, \"1P\", 1000, 560, 60, SILVER)\n",
    "            draw_text(screen, \"HI SCORE\" + str(HI_SCORE),1230,600,50,SILVER)\n",
    "            draw_text(screen, \"SCORE\" + str(score),1250, 560, 50, WHITE)\n",
    "            screen.blit(img_shield, [980,630])\n",
    "            draw_text(screen,\"1p set\" + \" \" +  str(win1), 1010, 600, 50, WHITE)\n",
    "            pygame.draw.rect(screen, (64,32,32),[980+ss_shield*4, 630, (100-ss_shield)*4, 12])\n",
    "\n",
    "\n",
    "            # 2p\n",
    "            key2 = pygame.key.get_pressed()\n",
    "            move_starship2(screen, key2)\n",
    "            move_missile2(screen)\n",
    "            draw_effect2(screen)\n",
    "            draw_text2(screen, \"2P\", 1000, 30, 60, SILVER)\n",
    "            draw_text2(screen, \"HI SCORE\" + str(HI_SCORE2), 1230, 70, 50, SILVER)\n",
    "            draw_text2(screen, \"SCORE\" + str(score2),1250,30,50,WHITE)\n",
    "            screen.blit(img_shield2, [980,100])\n",
    "            draw_text(screen, \"2p set\" + \" \" + str(win2), 1010, 70, 50, WHITE)\n",
    "            pygame.draw.rect(screen, (64,32,32),[980+ss_shield2*4, 100, (100-ss_shield2)*4, 12])\n",
    "\n",
    "            \n",
    "            \n",
    "                    \n",
    "            \n",
    "            if ss_shield != 0 and ss_shield2 <= 0 or score2 <= 0:\n",
    "                if win1 == 0:\n",
    "                    draw_text(screen,\"1p Set+1!\", 480, 300, 100, WHITE)\n",
    "                    p1_count += 1\n",
    "                    if p1_count > 40:\n",
    "                        idx = 2\n",
    "                        win1 += 1\n",
    "                        p1_count = 10\n",
    "\n",
    "            \n",
    "                if win1 == 2:\n",
    "                    draw_text(screen, \"1P WIN\", 480, 400, 250, WHITE)\n",
    "                    p1_count += 1\n",
    "                    if p1_count > 40:\n",
    "                        draw_text(screen, \"Press [P] \", 480, 520, 80, WHITE)\n",
    "                    if key[K_p] == 1:\n",
    "                            idx = 0\n",
    "\n",
    "\n",
    "\n",
    "            \n",
    "\n",
    "                    \n",
    "                \n",
    "\n",
    "            if ss_shield2 != 0 and ss_shield <= 0 or score <= 0:\n",
    "                if win2 == 0:\n",
    "                    draw_text(screen, \"2p Set+1!\",480, 300, 100, WHITE)\n",
    "                    p1_count += 1\n",
    "                    if p1_count > 40:\n",
    "                        idx = 2\n",
    "                        win2 += 1\n",
    "                        p1_count = 10\n",
    "                        \n",
    "                        \n",
    "                if win2 == 2:\n",
    "                    draw_text(screen, \"2P WIN\", 480, 400, 250, WHITE) \n",
    "                    p1_count += 1\n",
    "                    if p1_count > 40:\n",
    "                        draw_text(screen, \"Press [P] \", 480, 520, 80, WHITE)\n",
    "                    if key[K_p] == 1:\n",
    "                        idx = 0\n",
    "\n",
    "                            \n",
    "\n",
    "            if timetmr == 0 and ss_shield > 0 and ss_shield2 > 0:\n",
    "                draw_text(screen, \"TIME OVER\", 480, 250, 80, WHITE)\n",
    "                \n",
    "\n",
    "                if HI_SCORE > HI_SCORE2:\n",
    "                    if win1 == 0:\n",
    "                        draw_text(screen, \"1P Set+1!\", 480, 300, 100, WHITE)\n",
    "                        p1_count += 1\n",
    "                        if p1_count > 40:\n",
    "                            idx = 2\n",
    "                            win1 += 1\n",
    "                            p1_count = 10\n",
    "                    \n",
    "                    if win1 == 2:\n",
    "                        draw_text(screen, \"1P WIN\", 480, 400, 250, WHITE)\n",
    "                        p1_count += 1\n",
    "                        if p1_count > 40:\n",
    "                            draw_text(screen, \"Press [p] \", 480, 520, 80, WHITE)\n",
    "                        if key[K_p] == 1:\n",
    "                            idx = 0\n",
    "                \n",
    "                    \n",
    "                    \n",
    "                    \n",
    "                elif HI_SCORE < HI_SCORE2:\n",
    "                    if win2 == 0:\n",
    "                        draw_text(screen, \"2P Set+1!\", 480, 300, 100, WHITE)\n",
    "                        p1_count += 1\n",
    "                        if p1_count == 40:\n",
    "                            idx = 2\n",
    "                            win2 += 1\n",
    "                            p1_count = 10\n",
    "                            \n",
    "                    if win2 == 2:\n",
    "                        draw_text(screen, \"2P WIN!\", 480, 400, 250, WHITE)\n",
    "                        p1_count += 1\n",
    "                        if p1_count > 40:\n",
    "                            draw_text(screen, \"Press [p]\", 480, 520, 80, WHITE)\n",
    "                        if key[K_p] == 1:\n",
    "                            idx = 0\n",
    "                            \n",
    "                    \n",
    "                    \n",
    "                elif HI_SCORE == HI_SCORE2: \n",
    "                    draw_text(screen, \"DRAW MATCH\", 480, 300, 100, WHITE)\n",
    "                    p1_count += 1\n",
    "                    if p1_count == 40:\n",
    "                        idx = 2\n",
    "        if idx == 2:\n",
    "            if 40 < p1_count < 70:\n",
    "                draw_text(screen, \"NEXT_ROUND\", 510, 380, 80, SILVER)\n",
    "            p1_count += 1\n",
    "            if 70 < p1_count < 100:\n",
    "                draw_text(screen, \"GO\", 480, 350, 70, SILVER)\n",
    "                \n",
    "            if win1 == 1:\n",
    "                win1 = 2\n",
    "                \n",
    "            if win2 == 1:\n",
    "                win2 = 2\n",
    "                \n",
    "            if p1_count > 100:\n",
    "                idx = 1.5\n",
    "                p1_count = 0\n",
    "            \n",
    "            \n",
    "            \n",
    "            \n",
    "\n",
    "         \n",
    "        pygame.display.update()\n",
    "        clock.tick(60)\n",
    "\n",
    "                \n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "                \n",
    "        \n",
    "\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92efe61b-ba58-4622-8f5f-2ca5edfb9978",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bcd629f3-6bb8-4100-9cb9-909257991112",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c32e7e82-37fd-4e28-a210-8cfbbb4c8fda",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da04acec-03da-4346-950b-fc4290dbbc07",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "955e03b6-3f5d-4269-b2a3-f412511a71bb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d190558c-f1f9-4c5c-bf96-7e0c2a79d7ff",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96eb5048-bf5a-43b0-b38e-552fc9a47905",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7376475a-9191-4471-bb79-a49e50ce5bc3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "030e9039-fb4a-4d88-bc46-8c89d669606b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "486caba1-2059-4d6f-84b8-871b54b8042e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3470e9d-d9e0-4781-83f5-390df28442af",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b76c9ba-10e2-4d2f-972d-4b9239f9bc07",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0de874f1-d906-4d26-997e-f24a8707613c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bdd7cdc8-cbc4-4057-9ab9-5f740ab397bf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1cc58b63-c817-4b61-99be-e3a3f66aea79",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4e16bef-5f7d-40bd-a0b1-4551dc26af57",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c326a78c-8866-4430-b743-9b9ef9137e3d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d023cc8-b561-44a2-9d81-87e8a74fab91",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
